# -*- coding: utf-8 -*-
"""Proyecto_Final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17S-UDVQySwqwpf5LqeyLHo_SleMGtvQp
"""

!pip install flask_ngrok
!pip install pyngrok==4.1.1   
!ngrok authtoken 2OhokiiPdAj2opRcxbHsZPLcQol_6vPCHNpUHuDqueFoA78oF

from flask import Flask
from flask_ngrok import run_with_ngrok

app=Flask(__name__)
run_with_ngrok(app)

@app.route("/")
def home():
  return "<h1>Probando....</h1>"

app.run()

from google.colab import drive
drive.mount('/content/gdrive')

from flask.templating import render_template
from flask import Flask
from flask_ngrok import run_with_ngrok
template_folder= '/content/gdrive/MyDrive/Colab Notebooks/Proyecto_ADA/template'
app= Flask(__name__, template_folder = template_folder)
run_with_ngrok(app)
@app.route("/")
@app.route("/home")
def home():
  return render_template('home.html')

app.run()